// Phoenix-413 standalone vector harness (NOT part of the daemon build).
// Compiles phoenix413.h against the canonical vectors generated by
// contrib/phoenix413/generate_phoenix_vectors.py and reports PASS/FAIL.
//
// Build (from src\, adjust the vcpkg root if needed):
//   cl /nologo /EHsc /O2 /I <vcpkg>\installed\x64-windows\include ^
//      test-phoenix413.cpp /link /LIBPATH:<vcpkg>\installed\x64-windows\lib ^
//      libcrypto.lib
// Run with libcrypto-3-x64.dll on PATH (vcpkg installed\x64-windows\bin).

#include <stdio.h>
#include "phoenix413.h"
#include "phoenix413_vectors.h"

int main()
{
    unsigned int nFailures = 0;
    for (unsigned int i = 0; i < PHOENIX413_VECTOR_COUNT; i++)
    {
        const Phoenix413Vector& v = PHOENIX413_VECTORS[i];
        const unsigned int nGot = Phoenix413_NextCompact(
            v.anchor_bits, v.anchor_parent_time, v.anchor_height,
            v.eval_height, v.parent_time);
        if (nGot != v.expect_bits)
        {
            printf("FAIL %-22s expect 0x%08x got 0x%08x\n",
                   v.name, v.expect_bits, nGot);
            nFailures++;
        }
    }
    if (nFailures == 0)
    {
        printf("PASS — all %u Phoenix-413 vectors match\n",
               PHOENIX413_VECTOR_COUNT);
        return 0;
    }
    printf("FAILED — %u of %u vectors mismatched\n",
           nFailures, PHOENIX413_VECTOR_COUNT);
    return 1;
}
